### ISSUE TITLE
New version of Pandas

### ISSUE THREAD

**Issue by jsmedmar** [TailorDev/docker-pandas#1]
Hey Tailor,

Thanks for sharing your docker image! wondering if its worth to add a new tag with pandas new version.

Best!

**Comment by jsmedmar** [comment]
?

**Comment by jmaupetit** [comment]
I have bumped a new release with `panda==0.18.1`. This new image is currently building and will be available in a few minutes (see: https://hub.docker.com/r/tailordev/pandas/builds/)

Hope you will enjoy it.

**Comment by jsmedmar** [comment]
Great man! Thank you
